language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Winston")'
  - if [ `uname` = "Linux" ]; then
      xvfb-run julia --check-bounds=yes -e 'using Pkg; Pkg.test("Winston", coverage=true)';
    elif [ `uname` = "Darwin" ]; then
      julia --check-bounds=yes -e 'using Pkg; Pkg.test("Winston", coverage=true)';
    fi
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Winston")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
